### ISSUE TITLE
들어올시 차단돼었다고나가짐

### ISSUE THREAD

**Issue by RHappyAnt** [EntryPointKR/K-SPAM#2]
제가 1.3버전을깔고 서버키고 서버들어가면 차단돼었다고 뜨고 안들어가짐
(붓테러도 안당함)

**Comment by entrypointkr** [comment]
@RHappyAnt
버킷 버전은 어떻게되시나요?

**Comment by RHappyAnt** [comment]
1.5.2 Spigot R 1.1
이요

**Comment by entrypointkr** [comment]
entrypoint_@naver.com
위 메일로 사용하고 계시는 아이피 주소 보내주시면 확인해드리겠습니다.
https://search.naver.com/search.naver?where=nexearch&query=%EB%82%B4%EC%95%84%EC%9D%B4%ED%94%BC&sm=top_hty&fbm=1&ie=utf8

**Comment by RHappyAnt** [comment]
39.117.0.78
입니다

**Comment by entrypointkr** [comment]
캐시 파일의 내용에 192.168.0.1 이 있어 발생하는 오류로 보입니다.
서버를 본인이 직접 열어 접속하시나요?

**Comment by RHappyAnt** [comment]
네

**Comment by entrypointkr** [comment]
@RHappyAnt 
해당 버그가 해결될 때까지 localhost 또는 127.0.0.1 로 접속해주시면 감사하겠습니다.
만약 위 주소로 연결이 안된다면 명령어 /kspamrem 192.168.0.1 을 입력해 사용해주세요.
버그는 빠른 시일 내에 해결하겠습니다.
제보 감사합니다.

**Comment by RHappyAnt** [comment]
네 개발자분도 좋은플러그인만들길 바래요

**Comment by entrypointkr** [comment]
네 감사합니다.

**Comment by entrypointkr** [comment]
@RHappyAnt 해결되었습니다.
https://github.com/EntryPointKR/K-SPAM/releases/latest
