### ISSUE TITLE
취약점 발견 했긴 했습니다..

### ISSUE THREAD

**Issue by mome0320** [EntryPointKR/K-SPAM#26]
취약점: jar 파일에 쓰기가 된다. 
결과: jar 파일을 변형을 시킬수 있고 web으로 통한 위조백신.jar를 다운 해서 덮을 수 있을 가능성이 있습니다.
해결 방법: 쓰기 권한과 삭제 권한을 못하게 어떻게 해야할텐데. 저는 그쪽에 약해서.. ㅇㅅㅇ

**Comment by entrypointkr** [comment]
플러그인이 로드될 시 읽기 전용으로 설정되게 했습니다.
