### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by Dunk52** [EntryPointKR/K-SPAM#27]
현제 제가 1.11.2 버전으로 서버를 제작하고있습니다.
현제 K-Security 으로 1.11.2 버전으로 사용이 잘되고있습니다만..
서버를 키고나서보니 Skript 를 K-Security 꺼로 바꿔야해서
바꿔보았는데 /Skript help 만 뜨고 작동이 되질않습니다.
그래서 원본 [Skript](https://github.com/bensku/Skript/releases) 2.2 버전으로 하니깐 작동이 잘됩니다.

서버킬때마다 Skript 을 새로받으라는 메시지좀 고쳐주시기바랍니다.

**Comment by entrypointkr** [comment]
https://github.com/EntryPointKR/Skript-for-KSecurity/releases/tag/1.11.2
위에서 KSecurity 전용 언오피셜 Skript v2.2 (1.11.2) 다운로드 가능합니다
