### ISSUE TITLE
신규 봇 프록시 IP가 발견되었습니다

### ISSUE THREAD

**Issue by BrainHostGroup** [EntryPointKR/K-SPAM#29]
210.147.203.97:80
13.114.144.169:3128
45.77.22.17:80
45.76.197.19:80
45.77.31.200:80
52.198.226.61:80
125.175.229.171:8080
153.127.78.209:80
108.61.182.9:8080
45.32.57.138:3128
45.77.26.58:3128
153.190.23.33:8080
219.127.253.43:80
104.215.56.166:80
106.186.22.65:8888
153.122.117.177:8080
210.150.28.218:80
153.122.117.197:8080
153.122.117.176:8080
13.73.25.58:80
183.181.54.244:80
153.122.117.186:8080
52.198.75.249:80
103.15.187.116:80
153.122.117.199:8080
153.122.117.202:8080
219.166.7.50:1024
153.122.117.201:8080
103.37.95.110:80
117.55.209.123:8080
117.55.209.124:8081
219.111.2.137:53281
117.55.209.126:8080
153.122.117.203:8080
153.122.117.200:8080
211.106.65.151:8080
112.216.16.250:3128
1.255.49.91:8080
59.8.177.225:65309
119.194.30.183:80
52.78.139.216:80
14.52.23.216:8080
52.79.167.14:3128
210.101.131.231:8080
121.140.126.250:3128
220.120.119.90:3128
211.44.183.97:3128
1.209.188.197:8080
59.14.241.76:53281
13.124.9.190:80
61.42.18.132:53281
210.101.131.229:8080
14.199.36.251:8888
47.90.99.226:8118
13.75.118.206:8080
58.176.46.248:8380
219.76.4.12:88
52.229.160.222:8080
47.90.46.132:3128
183.179.198.93:3128
27.122.12.45:3128
47.90.67.89:8888
116.48.136.128:8080
223.197.56.102:80
113.254.98.253:8080
39.109.3.181:80
113.254.30.193:808
61.221.75.130:8888
1.175.138.116:3128
203.74.4.4:80
203.74.4.0:80
203.74.4.2:80
203.74.4.6:80
59.126.48.8:80
203.74.4.7:80
203.74.4.5:80
203.74.4.1:80
203.74.4.3:80
114.27.133.125:3128
1.175.143.75:3128
114.42.107.115:53281
114.27.133.149:3128
52.170.219.211:3128
45.55.139.100:8080
159.203.123.120:3128
66.70.191.5:3128
204.14.154.98:53281
67.205.160.136:3128
54.166.185.231:3128
45.77.112.179:8118
96.11.241.130:8081
192.95.18.162:8080
67.205.188.26:3128
138.68.16.252:1080
23.94.223.106:8118
162.243.140.150:80
38.96.9.162:8008
35.202.130.8:80
209.66.199.30:8080
138.197.211.31:3128
184.185.166.27:8080
68.190.17.93:8080
165.29.146.25:8080
162.243.15.104:8080
64.183.94.45:8080
192.129.233.39:9001
209.79.65.140:8080
159.63.166.167:53281
100.42.95.68:8080
50.73.106.129:8080
192.129.221.31:9001
50.233.12.118:8080
54.183.249.207:3128
13.85.69.230:8080
45.55.194.88:3128
162.243.33.71:8080
199.168.148.148:10047
66.220.13.184:8080
198.71.172.54:80
69.84.79.34:53281
35.189.166.230:8118
47.91.233.131:8080
47.52.96.5:80
47.52.5.8:3128
45.55.71.3:8118
173.90.19.159:8888
45.76.55.34:8080
47.52.108.18:80
96.94.72.73:53281
13.58.157.58:3128
168.128.29.75:80
35.163.121.81:3128
71.163.36.196:65309
199.48.160.69:3128
98.124.121.102:53281
192.129.205.242:9001
192.129.151.199:9001
34.204.223.219:3128
107.182.111.102:8080
54.183.229.224:3128
45.55.130.221:8118
13.56.40.133:80
104.131.94.221:8080
54.225.238.140:80
208.72.145.14:53281
76.178.99.104:8080
8.33.32.23:53281
192.129.151.74:9001
66.70.191.215:1080
165.138.124.4:8080
45.55.56.92:8888
54.204.31.39:4000
69.91.225.221:8080
107.170.214.74:80
54.67.87.44:80
192.129.161.216:9001
209.213.22.14:53281
212.24.40.78:80
62.213.76.74:80
212.24.40.77:80
62.213.76.110:80
62.213.76.106:80
62.213.76.76:80
46.39.238.113:8081
178.251.142.178:8081
188.32.83.38:8081
188.255.12.241:8081
85.12.220.70:8081
37.204.253.2:8081
212.24.40.75:80
5.16.0.47:8080
83.242.233.185:53281
46.44.37.115:8081
93.90.220.11:880
193.24.196.152:8081
93.170.108.22:3128
188.32.151.186:8081
93.189.83.85:8081
78.24.41.100:8081
95.26.190.73:8080
178.205.78.29:8080
95.73.81.29:8080
95.182.97.180:8080
176.117.38.65:53281
212.24.39.22:80
91.135.216.51:53281
31.207.199.62:8080
89.249.245.223:53281
188.134.5.197:21320
109.62.132.243:8080
212.24.39.21:80
217.107.197.174:8081
46.63.179.140:8080
91.107.5.210:53281
188.32.79.247:8081
195.5.155.42:8080
178.216.34.165:53281
46.151.9.25:8081
217.107.71.14:8080
87.245.154.66:80
188.130.230.40:8081
178.141.2.100:8081
212.24.40.74:80
93.91.112.185:80
95.221.100.48:8081
46.191.189.235:53281
213.148.166.161:53281
178.205.101.112:8080
5.100.77.187:65309
82.149.207.86:8081
91.234.60.202:53281
46.148.193.246:8081
185.30.118.11:53281
46.150.163.234:65309
78.157.225.146:53281
94.228.203.1:8085
176.197.221.46:53281
112.254.181.171:8118
183.240.87.229:80
86.238.220.148:3128
176.31.175.213:4444
163.172.156.142:3128
193.70.38.116:80
195.154.102.125:3128
163.172.173.43:3128
178.33.68.20:85
212.83.164.85:80
163.172.86.64:3128
51.254.98.159:8080
5.196.68.47:3128
151.80.44.163:3128
167.114.224.6:80
46.105.214.133:3128
212.129.52.131:8081
78.193.56.236:8118
212.237.60.208:3128
212.237.15.128:80
5.152.158.4:8080
95.233.4.118:8080
212.237.52.151:3128

여기에 신규 봇 아이피가 발견되었습니다
봇테러 대역 업데이트 해줄수 있나요?

**Comment by entrypointkr** [comment]
피드백 감사합니다 하지만 프록시 IP 들을 추가하는 것은 명쾌한 방지법이 되지 못합니다.
현재 K-Security 에는 많은 문제들이 있으며 예정 중인 4.0 업데이트 때는 거의 모든 코드가 새로 쓰여야 합니다. 또한 봇 테러 확인을 외부 API 를 통한 프록시 체킹이 아닌 봇만이 가지는 특성을 이용하여 차단에 필요한 오버헤드를 극적으로 줄이고 이에 생기는 성능 이점을 얻는 것이 현재 4.0 의 로드맵입니다.

더 궁금한 점이나 이의가 있다면 질문하셔도 좋습니다

**Comment by entrypointkr** [comment]
프록시 체킹이 필요없는 4.0 개발 중이므로 이슈 닫겠습니다
