### ISSUE TITLE
1.12.1 버전용은 없나요

### ISSUE THREAD

**Issue by noy98** [EntryPointKR/K-SPAM#30]
1.12.1 버전에서는 명령어 구동 시 명령어 도움말만 나올 뿐 아무 동작도 하지 않네욥

**Comment by entrypointkr** [comment]
1.12.1 에서 정상작동 확인했습니다
명령어 사용이 잘못됐다면 도움말이 출력되는 건 정상입니다
명령어를 정확히 사용했음에도 도움말이 출력된다면 그 사용한 명령어와 서버로그를 첨부해주세요.
