### ISSUE TITLE
[!] 오류발생

### ISSUE THREAD

**Issue by llt1256** [EntryPointKR/K-SPAM#34]
K-Security-3.2.10[봇테러방지]
![k-s](https://user-images.githubusercontent.com/37111798/37035845-2dc932f8-2191-11e8-98da-7578fa949362.png)

버전은 1.7.10 
버킷 : PaperSpigot 1.7.10
자바 버전 8 - 161

**Comment by entrypointkr** [comment]
K-Security 와 전혀 관련없는 GAListener 문제입니다.
